# Lists and Tuples

List is one of the most powerful data structures in Python. The List data type is made with so much of efforts and every programmer from beginner, intermediate to an expert should understand how it works.

Lists are **mutable** collection of objects. i.e. they are container to store a set of values of any data type.

for example:

```{python}
myList = [ 'milk', 'cars', 14, False]
```

-   Lists are ordered. We can index them and access values.

-   Lists are heterogeneous. A list can contain different types of elements.

-   Lists are mutable. You can change values in them.

## Creating a Lists

```{python}
items = [1,2,3]
items1 = list('123')
items2=['123']
items3=[]
items3.append(7)
items2.append(8) # adds at the end of the list
items4=[1, 2, False, [4,5]]
print(items, items1, items2, items3, items4)

```

### Indexing and Slicing Lists

```{python}
myList = ['milk', 'cars', 14, False]
myList[0]
myList[-1]
myList[0::2]
```

### Modifying Lists

Unlike strings, lists are mutable. Its values can be changed.

```{python}
myList = ['milk', 'cars', 14, False]
myList[1] = 'Trucks'
myList
myList.insert(2,9)
myList
```

## Sorting List

The `list.sort()` method sorts the elements of a list in ascending or descending order:

```{python}
a= [4,1,2,7,5,3]
a.sort()
print(a)
a.sort(reverse=True)
print(a)
```

### Sorting using a key parameters:

```{python}
cities = ['Karachi', 'Lahore', 'Faisalabad', 'Hayderababd']
cities.sort(key=len)
print(cities)
cities.sort(key=len, reverse=True)
print(cities)
```

### Removing Elements from the list

```{python}
cities = ['Karachi', 'Lahore', 'Faisalabad', 'Hayderababd']
cities.pop(0) # will delete the value at index 0 an return its value
cities
cities.remove('Lahore')
cities
cities2= cities.copy() #create a copy of list
```

## Converting a String to a List

String can be convert to a list, as per spaces " " or any other special characters "\_", according to the users choice, are encountered. To do this we use the split() method.

### Syntax

`string.split('delimiter')`

```{python}
string = "I like Python"
print(string.split(" "))

string1 = "I_Like_Python"
print(string1.split("_"))

```

## Tuples

Tuples are collections of Python objects. They are similar to lists but the difference between them is that **tuples are immutable** while **lists are mutable**. Tuples are created by typing a sequence of items, separated by *commas*. Optionally, you can put the comma-separated values in parenthesis.

1.  Tuple1=(1,2,5,6)

2.  Tuple2=('a', "b", 'c', "d")

3.  Tuple3 = () #empty tuple

4.  Tuple4 = 5,3,1

5.  Tuple5 = ("London", "Tokyo", "Korea", 1986, 1640, 1948)

    **Note:** To create a single item tuple, you have to use a comma after the value.

```{python}
Tup1 = (5) # its not a tuple
Tup2 = (5,)
Tuple5 = ("London", "Tokyo", "Korea", 1986, 1640, 1948)
print(type(Tup1))
print(type(Tup2))
print(Tuple5.index("Korea"))
```

The values of **tuples** are stored at different index positions starting from zero. We can access the values by using their index positions inside square brackets. We can index or slice tuples like lists.

```{python}
a = (1, 2, 2, 1, 3, 1, 4,2)

print(a[0]) , print(a[4])

print(a.count(2)) # will return the number of times 2 occurs

print(a.index( 2)) # will return the index of first occurrence of 2
```

## Tuple Unpacking

With a special syntax, Python can **unpack** the values of a tuple and extract them into **single variables**.

```{python}
a,b,c = (1,2,3)
print(a)
print(b)
print(c)
 #or
coordinates = (4,5,6)
x,y,z = coordinates # same can be used to unpack a list
print(x)
```

The number of variables to the left and right side should be the same and it assigns each variable respectively.

## Lists Vs Tuples

### Methods Available for List:

```{python}
list = [2,3,5,7,11,13,17]
print(dir(list))
```

### Methods Available for Tuple:

```{python}
tuple = (1,4,9,16,25,36)
print(dir(tuple))

```

As we observe that list have more methods as compare with tuples, but this extra functionality comes at a price i.e. list occupy more memoray than tuple. let's have a look:

```{python}
import sys
print(help(sys.getsizeof))

list  = [1,2,3,4,5,6,7]
tuple = (1,2,3,4,5,6,7)
print("The Size of the List  is", sys.getsizeof(list ), 'bytes')
print("The Size of the Tuple is", sys.getsizeof(tuple), 'bytes')
```

when working with big data, this can be significant.

+-----------------+----------------------+
| List            | Tuples               |
+=================+======================+
| -   Add Data    | -   Can't be changed |
+-----------------+----------------------+
| -   Remove Data | -   Immutable        |
+-----------------+----------------------+
| -   Change Data | -   Made Quickly     |
+-----------------+----------------------+

let's have a look that how tuples are more efficient than lists:

time required to create 1000,000 lists and tuples of same size.

```{python}
import timeit
list_test = timeit.timeit(stmt="[1,2,3,4,5,6]", number=1000_000)
tuple_test = timeit.timeit(stmt="(1,2,3,4,5,6)", number=1000_000)
print('Time needed to make 1000000 lists: ', list_test)
print('Time needed to make 1000000 tuples: ', tuple_test)
```

## Exercise

1.  Create a list `a_list`, with the following elements `1`, `hello`, `[1,2,3]` and `True`.

2.  Find the first and last value of the list.

3.  Find the value stored at index 1 of `a_list`.

4.  Retrieve the elements stored at index 1, 2 and 3 of `a_list`.

5.  Concatenate the following lists `A = [1, 'a']` and `B = [2, 1, 'd']`

6.  Make the list of the PIN of 5 officers and sort them in ascending and descending order.

7.  Consider the following tuple and Find the length of the tuple, `genres_tuple` genres_tuple = ("pop", "rock", "soul", "hard rock", "soft rock", "R&B", "progressive rock", "disco")

8.  Access the element, with respect to index 3.

9.  Use slicing to obtain indexes 3, 4 and 5.

10. Find the index of `"disco".`

11. Generate a sorted List from the Tuple `C_tuple=(-5, 1, -3).`

12. Check that a python tuple can't be altered.

13. Find the sum of `list2 = [1,2,3,4]`.

14. Write a program to count the number of occurrences of 4 in `tuple1=(4,1,2,5,7,4,8,4,4)`

15. Reverse a list2 define above (Q.13) using index method.

16. Make the list of the words of "I am doing well"

17. sort the above created list as per length of the words in reverse order.

18. list1 = `[100, 200, 300, 400, 500]`, output = `[500,400,300,200,100]`

19. list2 = `[10, 20, [300, 400, [5000, 6000], 500], 30, 40]`, Expected output :

        [10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]

20. list1 = `["a", "b", ["c", ["d", "e", ["f", "g"], "k"], "l"], "m", "n"]` \# sub list to add `sub_list = ["h", "i", "j"]` Expected Output:

    `["a", "b", ["c", ["d", "e", ["f", "g","h","i","j"], "k"], "l"], "m", "n"]`

21. list1 = `[5, 10, 15, 20, 25, 50, 20]` Expected Output: `[5, 10, 15, 200, 25, 50, 20]`

22. list1 = `[5, 20, 15, 200, 25, 50, 220]` remove 20 from the list.
